# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b29c18086ef016b880ad9d11fa4fc9b76dd2b83cd271777784b8854d126d5cfa18df4b449ddf1eeeaa186381152b99e5c2c6219ae4b24c813de3eee9864d71d

test:
  secret_key_base: 788a057638482fb205f2695a90231ebc9df7d594d74ae8763779964400330fb023b2ea40570a2c747537a489403713184f5b9592392692f7c3fe1aa2029252ad

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
